openapi: 3.0.3
info:
  description: |
    An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search.
  title: Search API
  version: 1.0.0
servers:
- description: Local development server
  url: http://localhost:8080/api/v1
paths:
  /upload:
    options:
      summary: CORS preflight
      description: Responds to CORS preflight requests
      responses:
        '204':
          description: No Content
          headers:
            Access-Control-Allow-Origin:
              description: CORS allow origin
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: CORS allowed methods
              schema:
                type: string
              example: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              description: CORS allowed headers
              schema:
                type: string
              example: 'Content-Type'
    post:
      summary: Upload a text file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_upload_post_request'
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_upload_post_200_response'
        '400':
          description: Bad request (e.g. no file provided)

  /query:
    options:
      summary: CORS preflight
      description: Responds to CORS preflight requests
      responses:
        '204':
          description: No Content
          headers:
            Access-Control-Allow-Origin:
              description: CORS allow origin
              schema:
                type: string
              example: '*'
            Access-Control-Allow-Methods:
              description: CORS allowed methods
              schema:
                type: string
              example: 'POST, OPTIONS'
            Access-Control-Allow-Headers:
              description: CORS allowed headers
              schema:
                type: string
              example: 'Content-Type'
    post:
      summary: Query the uploaded document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_query_post_request'
      responses:
        '200':
          description: Query results returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_query_post_200_response'
        '400':
          description: Bad request (e.g. empty query or no file uploaded yet)
components:
  schemas:
    _upload_post_request:
      properties:
        file:
          description: The plain text file to upload
          format: binary
          type: string
      type: object
    _upload_post_200_response:
      example:
        message: File uploaded successfully
      properties:
        message:
          example: File uploaded successfully
          type: string
      type: object
    _query_post_request:
      properties:
        query:
          description: The query string
          example: renewable energy storage
          type: string
      type: object
    _query_post_200_response:
      example:
        results:
        - Snippet 1
        - Snippet 2
      properties:
        results:
          example:
          - Snippet 1
          - Snippet 2
          items:
            type: string
          type: array
      type: object
