openapi: 3.0.3
info:
  title: Search API
  version: 1.0.0
  description: |
    An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search.

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

paths:
  /upload:
    post:
      summary: Upload a text file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The plain text file to upload
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded successfully
        '400':
          description: Bad request (e.g. no file provided)
  
  /query:
    post:
      summary: Query the uploaded document
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The query string
                  example: renewable energy storage
      responses:
        '200':
          description: Query results returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: string
                    example: ["Snippet 1", "Snippet 2"]
        '400':
          description: Bad request (e.g. empty query or no file uploaded yet)

components:
  schemas: {}