// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 *   Search API
 *
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
	"os"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// UploadPost - Upload a text file
func (s *DefaultAPIService) UploadPost(ctx context.Context, file *os.File) (ImplResponse, error) {
	// TODO - update UploadPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, UploadPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, UploadPost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UploadPost method not implemented")
}

// QueryPost - Query the uploaded document
func (s *DefaultAPIService) QueryPost(ctx context.Context, queryPostRequest QueryPostRequest) (ImplResponse, error) {
	// TODO - update QueryPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, QueryPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, QueryPost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("QueryPost method not implemented")
}
