// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 *   Search API
 *
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * API version: 1.0.0
 */

package openapi




type QueryPost200Response struct {

	Results []string `json:"results,omitempty"`
}

// AssertQueryPost200ResponseRequired checks if the required fields are not zero-ed
func AssertQueryPost200ResponseRequired(obj QueryPost200Response) error {
	return nil
}

// AssertQueryPost200ResponseConstraints checks if the values respects the defined constraints
func AssertQueryPost200ResponseConstraints(obj QueryPost200Response) error {
	return nil
}
