// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 *   Search API
 *
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * API version: 1.0.0
 */

package openapi




type QueryPostRequest struct {

	// The query string
	Query string `json:"query,omitempty"`
}

// AssertQueryPostRequestRequired checks if the required fields are not zero-ed
func AssertQueryPostRequestRequired(obj QueryPostRequest) error {
	return nil
}

// AssertQueryPostRequestConstraints checks if the values respects the defined constraints
func AssertQueryPostRequestConstraints(obj QueryPostRequest) error {
	return nil
}
