// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 *   Search API
 *
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * API version: 1.0.0
 */

package openapi




type UploadPost200Response struct {

	Message string `json:"message,omitempty"`
}

// AssertUploadPost200ResponseRequired checks if the required fields are not zero-ed
func AssertUploadPost200ResponseRequired(obj UploadPost200Response) error {
	return nil
}

// AssertUploadPost200ResponseConstraints checks if the values respects the defined constraints
func AssertUploadPost200ResponseConstraints(obj UploadPost200Response) error {
	return nil
}
