// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Search API
 *
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/adumbdinosaur/react-go-spa/server/pkg/api"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := openapi.NewDefaultAPIService()
	DefaultAPIController := openapi.NewDefaultAPIController(DefaultAPIService)

	router := openapi.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
