/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface QueryPost200Response
 */
export interface QueryPost200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryPost200Response
     */
    'results'?: Array<string>;
}
/**
 * 
 * @export
 * @interface QueryPostRequest
 */
export interface QueryPostRequest {
    /**
     * The query string
     * @type {string}
     * @memberof QueryPostRequest
     */
    'query'?: string;
}
/**
 * 
 * @export
 * @interface UploadPost200Response
 */
export interface UploadPost200Response {
    /**
     * 
     * @type {string}
     * @memberof UploadPost200Response
     */
    'message'?: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Query the uploaded document
         * @param {QueryPostRequest} queryPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryPost: async (queryPostRequest: QueryPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queryPostRequest' is not null or undefined
            assertParamExists('queryPost', 'queryPostRequest', queryPostRequest)
            const localVarPath = `/query`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(queryPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upload a text file
         * @param {File} [file] The plain text file to upload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPost: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Query the uploaded document
         * @param {QueryPostRequest} queryPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryPost(queryPostRequest: QueryPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QueryPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryPost(queryPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.queryPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upload a text file
         * @param {File} [file] The plain text file to upload
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadPost(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UploadPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadPost(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.uploadPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Query the uploaded document
         * @param {DefaultApiQueryPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryPost(requestParameters: DefaultApiQueryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<QueryPost200Response> {
            return localVarFp.queryPost(requestParameters.queryPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upload a text file
         * @param {DefaultApiUploadPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadPost(requestParameters: DefaultApiUploadPostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<UploadPost200Response> {
            return localVarFp.uploadPost(requestParameters.file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * 
     * @summary Query the uploaded document
     * @param {DefaultApiQueryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    queryPost(requestParameters: DefaultApiQueryPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<QueryPost200Response>;

    /**
     * 
     * @summary Upload a text file
     * @param {DefaultApiUploadPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    uploadPost(requestParameters?: DefaultApiUploadPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UploadPost200Response>;

}

/**
 * Request parameters for queryPost operation in DefaultApi.
 * @export
 * @interface DefaultApiQueryPostRequest
 */
export interface DefaultApiQueryPostRequest {
    /**
     * 
     * @type {QueryPostRequest}
     * @memberof DefaultApiQueryPost
     */
    readonly queryPostRequest: QueryPostRequest
}

/**
 * Request parameters for uploadPost operation in DefaultApi.
 * @export
 * @interface DefaultApiUploadPostRequest
 */
export interface DefaultApiUploadPostRequest {
    /**
     * The plain text file to upload
     * @type {File}
     * @memberof DefaultApiUploadPost
     */
    readonly file?: File
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * 
     * @summary Query the uploaded document
     * @param {DefaultApiQueryPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public queryPost(requestParameters: DefaultApiQueryPostRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).queryPost(requestParameters.queryPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upload a text file
     * @param {DefaultApiUploadPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public uploadPost(requestParameters: DefaultApiUploadPostRequest = {}, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).uploadPost(requestParameters.file, options).then((request) => request(this.axios, this.basePath));
    }
}



