/* tslint:disable */
/* eslint-disable */
/**
 *   Search API
 * An API that allows uploading a plain text document and querying it for relevant snippets using fuzzy search. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

